### ISSUE TITLE
Can't build with VS2010

### ISSUE THREAD

**Issue by mgthompson** [simh/windows-build#1]
After VS2010 converts the solution and projects from the original VS2008 version the projects will not compile.

------ Build started: Project: BuildROMs, Configuration: Debug Win32 ------
Build started 4/28/2013 10:54:05 AM.
InitializeBuildStatus:
  Creating "..\BIN\NT\Project\simh\BuildROMs\Win32-Debug\BuildROMs.unsuccessfulbuild" because "AlwaysCreate" was specified.
ClCompile:
  sim_BuildROMs.c
LinkEmbedManifest:
  BuildROMs.vcxproj -> C:\GitHub\simh\Visual Studio Projects..\BIN\NT\Win32-Debug\BuildROMs.exe
FinalizeBuildStatus:
  Deleting file "..\BIN\NT\Project\simh\BuildROMs\Win32-Debug\BuildROMs.unsuccessfulbuild".
  Touching "..\BIN\NT\Project\simh\BuildROMs\Win32-Debug\BuildROMs.lastbuildstate".

Build succeeded.

Time Elapsed 00:00:07.84
------ Build started: Project: VAX, Configuration: Debug Win32 ------
Build started 4/28/2013 10:54:13 AM.
InitializeBuildStatus:
  Creating "..\BIN\NT\Project\simh\VAX\Win32-Debug\VAX.unsuccessfulbuild" because "AlwaysCreate" was specified.
PreBuildEvent:
  Description: Build Dependent ROM include File(s) & Check for required build dependencies & git commit id
E:\Program Files\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppCommon.targets(103,5): error MSB3073: The command "pushd ..
E:\Program Files\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppCommon.targets(103,5): error MSB3073: "C:\GitHub\simh\BIN\NT\Win32-Debug\BuildROMs"
E:\Program Files\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppCommon.targets(103,5): error MSB3073: popd
E:\Program Files\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppCommon.targets(103,5): error MSB3073: 
E:\Program Files\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppCommon.targets(103,5): error MSB3073: if not exist ../../windows-build/winpcap/Wpdpack/Include/pcap.h goto _notice
E:\Program Files\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppCommon.targets(103,5): error MSB3073: if not exist ../../windows-build/pthreads/pthread.h goto _notice
E:\Program Files\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppCommon.targets(103,5): error MSB3073: goto _good
E:\Program Files\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppCommon.targets(103,5): error MSB3073: 
E:\Program Files\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppCommon.targets(103,5): error MSB3073: :_notice
E:\Program Files\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppCommon.targets(103,5): error MSB3073: echo ****************************************************
E:\Program Files\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppCommon.targets(103,5): error MSB3073: echo ****************************************************
E:\Program Files\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppCommon.targets(103,5): error MSB3073: echo *\*  The required build support is not available.  **
E:\Program Files\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppCommon.targets(103,5): error MSB3073: echo ****************************************************
E:\Program Files\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppCommon.targets(103,5): error MSB3073: echo ****************************************************
E:\Program Files\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppCommon.targets(103,5): error MSB3073: type 0ReadMe_Projects.txt
E:\Program Files\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppCommon.targets(103,5): error MSB3073: exit 1
E:\Program Files\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppCommon.targets(103,5): error MSB3073: 
E:\Program Files\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppCommon.targets(103,5): error MSB3073: :_good
E:\Program Files\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppCommon.targets(103,5): error MSB3073: SET GIT_COMMIT_ID=
E:\Program Files\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppCommon.targets(103,5): error MSB3073: if not exist ...git-commit-id goto _NoId
E:\Program Files\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppCommon.targets(103,5): error MSB3073: for /F %%i in (...git-commit-id) do SET GIT_COMMIT_ID=%%i
E:\Program Files\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppCommon.targets(103,5): error MSB3073: :_NoId
E:\Program Files\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppCommon.targets(103,5): error MSB3073: SET OLD_GIT_COMMIT_ID=
E:\Program Files\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppCommon.targets(103,5): error MSB3073: if not exist .git-commit-id.h echo.>.git-commit-id.h
E:\Program Files\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppCommon.targets(103,5): error MSB3073: for /F "tokens=3" %%i in (.git-commit-id.h) do SET OLD_GIT_COMMIT_ID=%%i
E:\Program Files\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppCommon.targets(103,5): error MSB3073: if "%GIT_COMMIT_ID%" equ "%OLD_GIT_COMMIT_ID%" goto _IdGood
E:\Program Files\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppCommon.targets(103,5): error MSB3073: echo #define SIM_GIT_COMMIT_ID %GIT_COMMIT_ID% >.git-commit-id.h
E:\Program Files\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppCommon.targets(103,5): error MSB3073: :_IdGood
E:\Program Files\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppCommon.targets(103,5): error MSB3073: 
E:\Program Files\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppCommon.targets(103,5): error MSB3073: :VCEnd" exited with code 1.

Build FAILED.

Time Elapsed 00:00:01.14
========== Build: 1 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by markpizz** [comment]
What OS are you running on?

**Comment by mgthompson** [comment]
XP Pro SP 3.

On Sun, Apr 28, 2013 at 11:51 AM, Mark Pizzolato
notifications@github.comwrote:

> What OS are you running on?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/simh/windows-build/issues/1#issuecomment-17136215
> .

## 

Michael Thompson

**Comment by markpizz** [comment]
The problem is not VS2010 related.  We've intentionally used the VS2008 project definitions since they will auto convert to working projects with both VS2010 and VS2012.  This has been tested and shown to work.

I see you are trying to build the VAX simulator.  Are you looking to make changes to it?  Don't the precompiled binaries work for you?

I honestly haven't tried to use XP for development for more than 6 years.  

I don't know of anyone else trying to build with visual studio on XP.

Meanwhile, other folks have and they've had success when compiling with MinGW.

All of that said, it might be possible to get a build to work cleanly, but I can't really tell from the above output what actually failed.  All of the commands in the PreBuildEvent are output but the first line starts with an error, so I'm not getting any real hints.

As I mentioned, I don't have a working XP development environment and it would be a very significant effort to put one together.

Please answer the above questions I raised and maybe we can figure a way to help you move forward.

You may want to contact me offline directly at mark@infocomm.com.

Thanks.
- Mark

**Comment by mgthompson** [comment]
Mark fixed everything. It works nicely now.
